/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "secondary": "#0050cc",
        "on-secondary": "#ffffff",
        "secondary-container": "#0266ff",
        "on-secondary-container": "#f9f7ff",
        "secondary-fixed": "#dae1ff",
        "secondary-fixed-dim": "#b3c5ff",
        "on-secondary-fixed": "#001849",
        "on-secondary-fixed-variant": "#003fa4",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-container": "#848484",
        "background": "#fbf9f9",
        "on-background": "#1b1c1c",
        "surface": "#fbf9f9",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e3e2e2",
        "on-surface-variant": "#4c4546",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fbf9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e2",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        "2xl": "80px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
